[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
eth_rpc_url = "https://stylish-fittest-scion.discover.quiknode.pro/00d47930a4d043653f16458d06b0476e285b5948/"
fork_block_number = 11128633